remote_theme: pmarsceill/just-the-docs

# jekyll
title: test title
description: Test description
future: false
color_scheme: dark

# for just-the-docs

ga_tracking: UA-198859322-1
ga_tracking_anonymize_ip: true
