remote_theme: pmarsceill/just-the-docs

# jekyll
title: Sinoalice Global Guides
description: Sinoalice Global Guides
future: false
color_scheme: dark
plugins:
 - jekyll-sitemap

# for just-the-docs

ga_tracking: UA-198859322-1
ga_tracking_anonymize_ip: true

# seo tag
title: Sinoalice Global Guides
author: soagg
tagline: Sinoalice explained
